### PR TITLE
added new key profiles and some basic description

### PR DESCRIPTION
**Pull request by angelfaraldo**

### CODE REVIEW

**Comment by angelfaraldo** [comment]
I don't think I touched any notation, did I? Just added very short descriptions of the context of each profile and added one refference

**Comment by angelfaraldo** [comment]
so how to merge this with onto the official essentia?

**Comment by dbogdanov** [comment]
@angelfaraldo I mean, we should use "A#" instead of "Bb", etc.

**Comment by angelfaraldo** [comment]
renamed!

**Comment by dbogdanov** [comment]
Thank you!!

**Pull request merged**
