### PR TITLE
Allow filtering negative energy values

### PR DESCRIPTION
**Pull request by alastair**
The PredominantPitchMelodia algorithm can return negative confidence
values if guessUnvoiced=True. This adds a new option to PitchFilterMakam
to automatically take the absolute value of any negative values.
Also fix a problem where the octaveFilter parameter wasn't being loaded
properly

### CODE REVIEW

**Comment by alastair** [comment]
Interesting comment here, is it true?
https://github.com/MTG/essentia/blob/pitchfiltermakam/src/algorithms/tonal/pitchfiltermakam.cpp#L326-L328

**Comment by sertansenturk** [comment]
Just checked the original code. Here is how the "energy" is computed:

```
            sig = wavread(audioFile);

            [...]

            %compute average signal amplitude
            [chunkSig]=mean(sig(audioStartInd:audioStopInd,:),2);
            aveAmp=sum(abs(chunkSig))/length(chunkSig);
```

As far as I understand, this is problematic since it gets the average of
the raw signal, i.e. the average amplitude a chunk with a pure sine and a
duration of a multiple period of the sine would be 0.

**Comment by sertansenturk** [comment]
Also, the threshold seems to be 6^2 = 36 instead of 6: https://github.com/MTG/essentia/blob/pitchfiltermakam/src/algorithms/tonal/pitchfiltermakam.cpp#L340

Nevertheless should we make this threshold an optional parameter?

**Comment by dbogdanov** [comment]
@sertansenturk having a parameter would be nice. Maybe, the matlab implementation also use 6? 
@alastair in any case (signal energy, spectral energy) we will now remove the notion of energy in general. We can state in docs that one can use signal energy (as suggested by the paper) or spectral energy instead of confidence values.

**Comment by sertansenturk** [comment]
@dbogdanov yes it does. I'm pasting the whole code below as a reference:

```
%[f0track]=FILTERF0(f0track,octavFiltFlag,minChunkSize,windowShiftSample,audioFile)
%    Post-filtering to: 
%           - remove sudden jumps in the f0 curve
%           - assign zero cents frequency to noisy f0 regions
%           - filter out outliers (too high frequencies)
%    Setting 'octavFiltFlag', octave error correction filter is enabled.
%    windowShiftSample: number of samples (hop size) in YIN analysis
%    Wave file is utilized in filters using signal energy information

% IYTE-Audio Pro. Lab. SOFTWARE LIBRARY
% Date: <September/2008>
% Authors: Baris Bozkurt
% Email :  bozkurt@tcts.fpms.ac.be
% Copyright (c) Izmir Institute Of Technology, Audio Processing Lab. 
% All rights reserved.


function [f0track]=filterf0(f0track,octavFiltFlag,minChunkSize,windowShiftSample,audioFile)

%-----------------------------------
[f0track]=correctOctErrByChnk(f0track);
%-----------------------------------
%removing extreme values-----------
%get histogram
maxf0=max(f0track);
histEdges=0:100:maxf0;
n=histc(f0track,histEdges);
%find ranges where no pitch estimation exists
zeroInd=find(n==0);
if(length(zeroInd)>2)
    k=1;
    while((zeroInd(k)~=zeroInd(k+1)-1) && k<(length(zeroInd)-1))
        k=k+1;
    end
    if(k<length(zeroInd)-1)
        if(sum(n(1:zeroInd(k)))>(sum(n)*0.9))%higher values are outliers
            maxf0=histEdges(zeroInd(k)+1);
        end
    end
end
meanf0=mean(f0track);
stdf0=std(f0track);
candMaxf0=max(meanf0*4,meanf0+2*stdf0);
maxf0=min(maxf0,candMaxf0);
%find indices of estimates exceeding maxval
maxInd=find(f0track>maxf0);
f0track(maxInd)=8.17579891564371;
%find indices of estimates lower than minval
minf0=mean(f0track)/4;
minInd=find(f0track<minf0);
f0track(minInd)=8.17579891564371;

%-----------------------------------
%correct jumps/discontinuities within continuous curves
[f0track]=correctJumps(f0track);
%the same operation on the inverse
f0track=f0track(end:-1:1);
[f0track]=correctJumps(f0track);
f0track=f0track(end:-1:1);
%-----------------------------------
%assigns zero cents frequency to noisy f0 regions
for m=1:3
    for k=2:length(f0track)-2%3 seperate points, assign 0 to mid
        if(~areClose(f0track(k-1),f0track(k)) && ~areClose(f0track(k),f0track(k+1)))
            f0track(k)=8.17579891564371;
        end
    end
    for k=3:length(f0track)-3%4 points, 2 in mid are similar but different from the boundaries, assign 0 to mid two
        if(~areClose(f0track(k-2),f0track(k)) && ~areClose(f0track(k-1),f0track(k)) && ~areClose(f0track(k+1),f0track(k+2)) && ~areClose(f0track(k+1),f0track(k+3)))
            f0track(k:k+1)=8.17579891564371;
        end
    end
end
%-----------------------------------
%filter out noise like variations
for k=2:length(f0track)-2
    if(~areClose(f0track(k-1),f0track(k)) && ~areClose(f0track(k),f0track(k+1)) && ~areClose(f0track(k+1),f0track(k+2)))
        if(~areClose(f0track(k-1),f0track(k+1)) && ~areClose(f0track(k),f0track(k+2)))
            if(~areClose(f0track(k-1),f0track(k+2)))
                f0track(k:k+1)=8.17579891564371;
            end
        end        
    end
end
%-----------------------------------
%filter that corrects octave errors
if(octavFiltFlag)
    [f0track]=correctOctaveErr(f0track);
    %the same operation on the inverse
    f0track=f0track(end:-1:1);
    [f0track]=correctOctaveErr(f0track);
    f0track=f0track(end:-1:1);
end
%-----------------------------------
[f0track]=correctOctErrByChnk(f0track);
%-----------------------------------
%filter short chunks with low energy
[f0Chunks,chunkLengths]=decomposeIntoChunks(f0track);
%find longest chunk
[val,maxInd]=max(chunkLengths);
%compute average signal amplitude in the longest chunk
audioStartInd=f0Chunks(maxInd).startIndex*windowShiftSample;
audioStopInd=(f0Chunks(maxInd+1).startIndex-1)*windowShiftSample;
if verLessThan('matlab', '8.1')
    [chunkSig]=wavread(audioFile,[audioStartInd audioStopInd]);
else
    [chunkSig]=audioread(audioFile,[audioStartInd audioStopInd]);
end
aveAmpLongest=sum(abs(chunkSig))/length(chunkSig);
aveAmpLimit=aveAmpLongest/6;

%filtering
if verLessThan('matlab', '8.1')
    sig = wavread(audioFile);
else
    sig = audioread(audioFile);
end
for k=1:length(f0Chunks)
    if(max(f0Chunks(k).f0)>8.2)%no need to run this filter for zero-frequency regions
        if(length(f0Chunks(k).f0)<minChunkSize)
            f0Chunks(k).f0=f0Chunks(k).f0*0+8.17579891564371;
        elseif(length(f0Chunks(k).f0)<minChunkSize*3 && k<length(f0Chunks))%filtering short chunks with low signal energy
            %compute average signal amplitude
            audioStartInd=f0Chunks(k).startIndex*windowShiftSample;
            audioStopInd=(f0Chunks(k+1).startIndex-1)*windowShiftSample;
            [chunkSig]=mean(sig(audioStartInd:audioStopInd,:),2);
            aveAmp=sum(abs(chunkSig))/length(chunkSig);
            if(aveAmp<aveAmpLimit)
                f0Chunks(k).f0=f0Chunks(k).f0*0+8.17579891564371;
            end
        end
    end
end
[f0track]=recomposeChunks(f0Chunks);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [f0track]=correctJumps(f0track)
%each time, it assures that three boundaries on both sides are in fact continuous

for k=5:length(f0track)-6
    if(areClose(f0track(k-4),f0track(k-3)) && areClose(f0track(k-3),f0track(k-2)) && areClose(f0track(k-1),f0track(k-2)))
        %quadriple point        
        if(areClose(f0track(k+4),f0track(k+5)) && areClose(f0track(k+5),f0track(k+6)))
            if(~areClose(f0track(k),f0track(k-1)) && ~areClose(f0track(k),f0track(k+4)))
                f0track(k)=f0track(k-1);
            end
            if(~areClose(f0track(k+3),f0track(k-1)) && ~areClose(f0track(k+3),f0track(k+4)))
                f0track(k+3)=f0track(k+4);
            end          
        end
        %triple point
        if(areClose(f0track(k+3),f0track(k+4)) && areClose(f0track(k+4),f0track(k+5)))
            if(~areClose(f0track(k),f0track(k-1)) && ~areClose(f0track(k),f0track(k+3)))
                f0track(k)=f0track(k-1);
            end
            if(~areClose(f0track(k+2),f0track(k-1)) && ~areClose(f0track(k+2),f0track(k+3)))
                f0track(k+2)=f0track(k+3);
            end        
        end
        %double point
        if(areClose(f0track(k+2),f0track(k+3)) && areClose(f0track(k+3),f0track(k+4)))
            if(~areClose(f0track(k),f0track(k-1)) && ~areClose(f0track(k),f0track(k+2)))
                f0track(k)=f0track(k-1);
            end
            if(~areClose(f0track(k+1),f0track(k-1)) && ~areClose(f0track(k+1),f0track(k+2)))
                f0track(k+1)=f0track(k+2);
            end
        end
        %single point
        if(areClose(f0track(k+1),f0track(k+2)) && areClose(f0track(k+2),f0track(k+3)))
            if(~areClose(f0track(k),f0track(k-1)) && ~areClose(f0track(k),f0track(k+1)))
                f0track(k)=f0track(k-1);
            end
        end
    end
end

function [f0track]=correctOctaveErr(f0track)

midf0=(median(f0track)+mean(f0track))/2;
for k=5:length(f0track)-2
    %if previous values are continuous
    if(areClose(f0track(k-1),f0track(k-2)) && areClose(f0track(k-2),f0track(k-3)) && areClose(f0track(k-3),f0track(k-4)))
        if(f0track(k)>(midf0*1.8)) 
            if(areClose(f0track(k-1),f0track(k)/2))
                f0track(k)=f0track(k)/2;
            elseif(areClose(f0track(k-1),f0track(k)/4))
                f0track(k)=f0track(k)/4;
            end
        elseif(f0track(k)<(midf0/1.8))
            if(areClose(f0track(k-1),f0track(k)*2))
                f0track(k)=f0track(k)*2;
            elseif(areClose(f0track(k-1),f0track(k)*4))
                f0track(k)=f0track(k)*4;
            end
        end
    end
end


function [f0Chunks,chunkLengths]=decomposeIntoChunks(f0track)

f0Chunks=struct('f0',[],'startIndex',[]);
f0Chunks(1).startIndex=1;
ind=1;chunkLengths=[];
for k=1:length(f0track)-1
    f0Chunks(ind).f0=[f0Chunks(ind).f0 f0track(k)];
    f0interval=f0track(k+1)/f0track(k);
    if(f0interval<0.80 || f0interval>1.2)
        ind=ind+1;
        f0Chunks(ind).f0=[];
        f0Chunks(ind).startIndex=k+1;%keeps start index for each chunk within the whole f0track
        chunkLengths=[chunkLengths length(f0Chunks(ind-1).f0)];
    end
end
f0Chunks(ind).f0=[f0Chunks(ind).f0 f0track(end)];

function [newf0track]=recomposeChunks(f0Chunks)
%reconstruction
newf0track=[];
for k=1:length(f0Chunks)
    newf0track=[newf0track f0Chunks(k).f0];
end

function [f0track]=correctOctErrByChnk(f0track)
%-----------------------------------
%correct octave errors by chunks
%decompose into chunks
[f0Chunks,chunkLengths]=decomposeIntoChunks(f0track);
%correct octave errors in chunks
for k=2:length(f0Chunks)-1
    if(length(f0Chunks(k).f0)<max(length(f0Chunks(k-1).f0),length(f0Chunks(k+1).f0)))
        if(areClose(f0Chunks(k).f0(1)/2,f0Chunks(k-1).f0(end)) && f0Chunks(k).f0(end)/1.5>f0Chunks(k+1).f0(1))
            f0Chunks(k).f0=f0Chunks(k).f0/2;
        elseif(areClose(f0Chunks(k).f0(end)/2,f0Chunks(k+1).f0(1)) && f0Chunks(k).f0(1)/1.5>f0Chunks(k-1).f0(end))
            f0Chunks(k).f0=f0Chunks(k).f0/2;
            %----------------------------------
        elseif(areClose(f0Chunks(k).f0(1)*2,f0Chunks(k-1).f0(end)) && f0Chunks(k).f0(end)*1.5<f0Chunks(k+1).f0(1))
            f0Chunks(k).f0=f0Chunks(k).f0*2;
        elseif(f0Chunks(k).f0(1)*1.5<f0Chunks(k-1).f0(end) && areClose(f0Chunks(k).f0(end)*2,f0Chunks(k+1).f0(1)))
            f0Chunks(k).f0=f0Chunks(k).f0*2;
        end
    end
end
[f0track]=recomposeChunks(f0Chunks);
```

**Comment by alastair** [comment]
I've renamed the file, renamed energy to confidence, updated the docs, and made the threshold value a parameter.

**Comment by dbogdanov** [comment]
As @sertansenturk said, the matlab implementation also uses threshold of 6. May be this should be the default value. Does the filtering works better with 36 instead of 6?

**Comment by sertansenturk** [comment]
@hsercanatli is going to find a plausible default for the threshold. He will check it in the weekend.

**Comment by sertansenturk** [comment]
- Barış's original code uses 100ms minimum chunkSize. Melodia also uses the same. Since Melodia (128 sample) and YIN (2048? samples) has different default  hopSizes, this parameter cannot have a "default" value that translates to the same duration. I think we can make the default as 30 and mention this maps to ~100ms with 128 sample hopSize of Melodia.
- With our own [code](https://github.com/MTG/pycompmusic/blob/master/compmusic/extractors/makam/pitch.py) for makam music, confidenceThreshold does not change much. This is because [removeExtremeValues](https://github.com/MTG/essentia/blob/pitchfiltermakam/src/algorithms/tonal/pitchfilter.cpp#L84) and [filterNoiseRegions](https://github.com/MTG/essentia/blob/pitchfiltermakam/src/algorithms/tonal/pitchfilter.cpp#L92) take care of most of the errors before it reaches to [filterChunksByPitchConfidence](https://github.com/MTG/essentia/blob/pitchfiltermakam/src/algorithms/tonal/pitchfilter.cpp#L103). Also samples with low confidence are usually seen in the end of chunks (e.g. reverb). Since we are working on the chunk level, filterChunksByPitchConfidence is not able to do anything meaningful. I think we should just keep the default as 36 for now.
- Even if we have the octaveFilter parameter set to false, we are still introducing octave corrections in [line 83](https://github.com/MTG/essentia/blob/pitchfiltermakam/src/algorithms/tonal/pitchfilter.cpp#L83). This is called earlier as it will contribute to the removeExtremeValues (the next line). Maybe, we should just remove this optional parameter.

**Comment by dbogdanov** [comment]
I don't know if an option to skip octave correction may be useful for somebody. If so, we can keep the option, otherwise, remove. Anybody from CompMusic guys ever used it?

Another solution would be to have another if statement on line [83](https://github.com/MTG/essentia/blob/pitchfiltermakam/src/algorithms/tonal/pitchfilter.cpp#L83), but that might affect the algorithm in a bad way.

**Comment by sertansenturk** [comment]
From this version the makam guys will start using it for sure :) 

Having said that for us the most important step in this code is actually octave correction. Your second solution seems plausible but given that we will use it for mostly octave correction, I don't think we need this optional argument for now.

**Comment by dbogdanov** [comment]
Cool, than get rid of it ;)

**Comment by sertansenturk** [comment]
:+1: 

Apart from this we are only going to change the default value of chunkSize to 30, right? Is there anything else to do before merging?

**Comment by dbogdanov** [comment]
These fixes are all we need.

**Comment by sertansenturk** [comment]
Since I cannot push to essentia repo, I've created a [pull request](https://github.com/MTG/essentia/pull/296) to this pitchfiltermakam branch.

In the meantime I inspected the confidence values a little bit. I think we should work with the confidences in the log domain. I'll return with a brief explanation shortly.

**Comment by sertansenturk** [comment]
There is no way to find an easy optimum for ConfidenceThreshold as it is dependent on the quality of the recording. I have observed that historical makam recordings need a higher value so that the melody is not lost to background, commercial instrumental recordings need it lower. Several commercial vocal recordings I checked seems to be fine with our current default (36) such that the melody in the instrumental preludes or sections with lower energy are not still tracked. Let's keep the default value as is...

**Comment by alastair** [comment]
I've merged sertan's changes into this branch. We're ready to merge to master.

**Comment by sertansenturk** [comment]
One thing that popped into my mind.

I haven´t done anything on the documentation. because I couldn´t find where it is The octaveFilter should be still there and the value of minChunkSize should be the old one.

**Comment by alastair** [comment]
parameters and default values are added to the documentation automatically based on the code

**Pull request merged**
