### PR TITLE
Check if an array is a view or a copy

### PR DESCRIPTION
**Pull request by pabloEntropia**
Modification in the python parser in order to check if an input numpy array is a view or a copy. If it is a view, it copies the data to a new array. 
There is also a base test in order to check the proper behavior.

### CODE REVIEW

**Comment by dbogdanov** [comment]
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ascontiguousarray.html

**Comment by dbogdanov** [comment]
Use C_CONTIGUOUS flag instead of OWNDATA

**Comment by seffka** [comment]
Is this fix aimed for all Algorithms?
Have an issue with standard.Slicer algorithm and sliced arrays. After upgrade to latest dev version it's still here.

**Comment by dbogdanov** [comment]
Should be fixed now.

**Pull request merged**
