### PR TITLE
iOS support

### PR DESCRIPTION
**Pull request by carthach**
Support for cross compiling on iOS from OS X in lightweight mode. Configure like this:

./waf configure --cross-compile-ios --lightweight= --fft=ACCELERATE --build-static

Tested on an iPad-Air. There's also a flag to build for the simulator (so you can test on the Desktop)

### CODE REVIEW

**Comment by dbogdanov** [comment]
I am testing the build. The library is built, but I get a warning in the end: 
```
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: src/libessentia.a will be fat and ar(1) will not be able to operate on it
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: armv7 file: src/libessentia.a(essentiautil.cpp.1.o) has no symbols
```

**Comment by carthach** [comment]
Yeh dunno what that is, prob something to do with the fact that it's building a fat library (armv7 and arm64).

Still works though..

**Comment by dbogdanov** [comment]
Thanks!

**Comment by iOSzhangkai** [comment]
> warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: src/libessentia.a will be fat and ar(1) will not be able to operate on it
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: armv7 file: src/libessentia.a(essentiautil.cpp.1.o) has no symbols


Excuse me, I've been compiling this Waring all the time, but the program still tells me that it's successful. There will be a libessentia.a file in /build/scr. How do I fit into the iOS project?

**Comment by carthach** [comment]
Depends on what framework and workflow you used.

I used JUCE to build this:
https://github.com/carthach/eear/tree/master/eear-Mobile

Not sure how you would get it to work with Objective C because I've never programmed using it. Plenty of tutorials about though so a bit of Google detective work should sort you out.

https://www.sitepoint.com/using-c-and-c-in-an-ios-app-with-objective-c/

Just remember that none of the audio loading or audio writing works in mobile versions of essentia, you need to use the ones provided by your platform.

**Comment by iOSzhangkai** [comment]
How can I put the audio data in essentia if it can not load the file from system? I havn't found out the method that can accept a input stream or other data type. Please help me. Thanks a lot.

**Pull request merged**
