### PR TITLE
Stop immediately if any command in a script fails

### LINKED ISSUE #986: Make 3rd party build scripts fail if any subcommand fails
We are using `build_3rdparty_static_debian.sh` in docker to build static dependencies. Sometimes, a part of one of these scripts fails, but then the rest of the build process continues. Docker thinks that everything is fine, because the scripts exited with a success code.

We should use bash's builtin `set -e` to cause these scripts to exit with an error if any subcommand fails. that way users can see immediately if some part of the process fails, and docker build will correctly stop if an error occurs.

### PR DESCRIPTION
**Pull request by amCap1712**
Fixes #986

### CODE REVIEW

**Comment by dbogdanov** [comment]
Thanks! As this is `bash` functionality we also need to change the shebang to `#!/usr/bin/env bash` in all the scripts updated in this PR.

We require [signing the Essentia and Gaia Individual Contributor License Agreement](https://essentia.upf.edu/contribute.html) for contributions larger than 20 lines of code. Can you take care of this before we merge your PRs?

**Comment by amCap1712** [comment]
@dbogdanov I have emailed the CLA. I'll fix the shebangs by tomorrow.

**Comment by amCap1712** [comment]
@dbogdanov Done.

**Comment by dbogdanov** [comment]
Looks good now. Thanks!!

**Pull request merged**
