### PR TITLE
Use libswresample instead of libavresample

### PR DESCRIPTION
**Pull request by Martchus**
see https://github.com/MTG/essentia/issues/808

### CODE REVIEW

**Comment by dbogdanov** [comment]
Hi @Martchus,

Thank you for the PR! We are about to switch to libswresample. Can you submit a [CLA form](https://essentia.upf.edu/contribute.html)?

**Comment by Martchus** [comment]
I can do that later (and resolve conflicts).

**Comment by Martchus** [comment]
I've sent the CLA to the email address mentioned in the linked page. I've also rebased resolving the conflict in the build script. I've also replaced the Debian package `libavresample-dev` with `libswresample-dev` where it was mentioned. It seems available on all Ubuntu versions searchable on their package search (see https://packages.ubuntu.com/search?suite=bionic&arch=any&searchon=names&keywords=swresample).

**Comment by Martchus** [comment]
So, is anything missing?

**Comment by dbogdanov** [comment]
Hi @Martchus,
sorry for delay, it appears our administration has never received the email. Could you resend it to `mtg-info@upf.edu`?

**Comment by Martchus** [comment]
I've just sent the e-mail to the mentioned address (before I sent it to `mtg@upf.edu`).

**Comment by Martchus** [comment]
It happened :-)

**Pull request merged**
